server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 3128
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/onlinebanking

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    '[com.example.notification]': DEBUG

example:
  notification:
    services:
      account-service-url: http://localhost:8081

    rabbitmq:
      queues:
        transaction-created: transaction.created.queue
        account-created: account.created.queue


---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-notification:5432/notification_db
    username: postgres
    password: 3128

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/onlinebanking
          jwk-set-uri: http://keycloak:8080/realms/onlinebanking/protocol/openid-connect/certs

example:
  notification:
    services:
      account-service-url: http://account-service:8081